[project]
name = "farasapy"
version = "0.1.0"
description = "A Python Wrapper for the well Farasa toolkit"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black==24.3.0",
    "bleach==3.3.0",
    "pylint==2.5.2",
    "requests==2.32.3",
    "tqdm==4.66.3",
]
